apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helloappset
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/tmp120210/keptstore-demo.git
      revision: HEAD
      directories:
      - path: 'deployments/*'
  - list:
      elements:
      - cluster: engineering-dev
        url: https://kubernetes.default.svc
      - cluster: engineering-prod
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{.path.basename}}-helloapp'
    spec:
      project: default
      source:
        repoURL: https://github.com/tmp120210/keptstore-demo.git
        targetRevision: HEAD
        path: deploy
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{.path.basename}}'
      syncPolicy:
        automated: {}
        syncOptions:
        - CreateNamespace=true