apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/tmp120210/keptstore-demo.git
      revision: HEAD
      files:
      - path: "deployments/**/config.json"
  template:
    metadata:
      name: '{{.cluster.name}}-guestboo4k'
    spec:
      project: default
      source:
        repoURL: https://github.com/tmp120210/keptstore-demo.git
        targetRevision: HEAD
        path: deploy
      destination:
        server: '{{.cluster.address}}'
        namespace: '{{.cluster.name}}'
      syncPolicy:
        automated: 
          prune: true
          allowEmpty: true
        syncOptions:
        - CreateNamespace=true      