apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helloappset
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  # - list:
  #     elements:
  #     - cluster: engineering-dev
  #       url: https://kubernetes.default.svc

  - git:
      repoURL: https://github.com/tmp120210/keptstore-demo.git
      revision: HEAD
      files:
      - path: "deployments/**/config.json"
      values:
        cluster: engineering-git
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{.cluster}}-helloapp'
    spec:
      project: default
      source:
        repoURL: https://github.com/tmp120210/keptstore-demo.git
        targetRevision: HEAD
        path: deploy
      destination:
        server: '{{.url}}'
        namespace: '{{.cluster}}'
      syncPolicy:
        automated: {}
        syncOptions:
        - CreateNamespace=true