apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - cluster: engineering-dev
      - cluster: engineering-prod
      - cluster: finance-preprod
        
  template:
    metadata:
      name: '{{.cluster}}-hello-app'
    spec:
      project: hello-app
      source:
        repoURL: https://github.com/tmp120210/keptstore-demo.git
        targetRevision: HEAD
        path: deploy
      destination:
        server: https://kubernetes.default.svc
        namespace: {{.cluster}}