apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helloapp
spec:
  destination:
    name: ''
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: deploy
    repoURL: https://github.com/tmp120210/keptstore-demo
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
