apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-delete-branch
spec:
  params:
  - name: username
    type: string
  - name: wait-time
    type: string
  workspaces:
    - name: output
  steps:
    - name: delete-branch
      image: docker.io/bitnami/git
      workingDir: $(workspaces.output.path)
      script: |
        #!/bin/bash
        set -eu
        wait_time=$(( $(params.wait-time) ))
        echo "Waiting for $wait_time seconds before deleting the branch..."
        sleep $wait_time
        git checkout master
        echo "Deleting branch $(params.username)..."
        git branch -D $(params.username)
        git push origin --delete $(params.username)