apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: create-demo
spec:
  params:
  - name: username
    type: string
  workspaces:
    - name: shared-workspace 
  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
        kind: Task
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
      - name: username
        value: $(params.username)
    - name: write-file
      taskRef:
        name: write-file
        kind: Task
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
      - name: path
        value: deployments/$(params.username)/config.json
      - name: contents
        value: |
          {
              "cluster": {
                  "name": "engineering-$(params.username)",
                  "address": "https://kubernetes.default.svc"
              }
          }
      runAfter:
        - git-clone
    - name: git-push
      taskRef:
        name: git-push
        kind: Task
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: username
          value: $(params.username)
      runAfter:
        - write-file
